spring:
  datasource:
    url: ${DATABASE_CONN_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET_KEY}
  exp-time: ${JWT_EXP_TIME}

stripe:
  api-key: ${STRIPE_API_KEY}

app:
  payment:
    timeout: ${PAYMENT_TIMEOUT}
    cleaner:
      delay: ${EXPIRED_PAYMENT_CLEANER_DELAY}