spring:
  datasource:
    url: ${DATABASE_CONN_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET_KEY}
  exp-time: ${JWT_EXP_TIME}

stripe:
  api-key: ${STRIPE_API_KEY}
  webhook-invoked-api-secret: ${STRIPE_WEBHOOK_INVOKED_API_SECRET}

app:
  payment:
    timeout: ${PAYMENT_TIMEOUT}
  order:
    cleanup-delay: ${EXPIRED_ORDER_CLEANUP_DELAY}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,scheduledtasks"
