spring:
  datasource:
    url: ${DATABASE_CONNECTION_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET_KEY}
  exp-time: ${JWT_EXPIRATION_TIME}

springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/ui.html

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  secret: ${PAYPAL_CLIENT_SECRET}