spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mrs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: Aymga2LNFrM+tnkr6MYLFY2Jou46h2/Omogeu0iMCRQ=
  exp-time: 999999

stripe:
  api-key: stripe_fake_api_key
  webhook-invoked-api-secret: stripe_fake_webhook_secret

app:
  payment:
    timeout: 5m
  order:
    cleanup-delay: 1m