spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mrs
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: Aymga2LNFrM+tnkr6MYLFY2Jou46h2/Omogeu0iMCRQ=
  exp-time: 999999

paypal:
  environment: SANDBOX
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}

logging:
  level:
    org.springframework.boot.context.config: DEBUG