name: Integration tests
on:
  push:
    branches: [ "main", "develop" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Check Docker version
        run: docker
      - name: List compiled integration tests
        run: ls -R target/test-classes
      - name: Run tests
        run: mvn clean verify -DskipUnitTests
